version: "3.9"

services:

  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hoopoe
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

  
  hoopoe:
    image: ghcr.io/emaddeve20/hoopoe:latest
    container_name: hoopoe
    ports:
      - 8000:8000
    volumes:
      - media:/app/hoopoe/media:rw
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: always


volumes:
  postgres-data:
    external: true
  redis-data:
    external: true
  media:
    external: true

