name: Hoopoe Build Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: build and publish docekr image
      run: |
        docker login --username EmadDeve20 --password ${{ secrets.GH_PAT }} ghcr.io
        ./build.sh

